"""Backward-compatible facade: imports moved to game_pkg/. (no logic here)."""
from game_pkg.config import (
    STARTER_WEAPON,
    STARTER_ABILITY,
    DEEP_WATER_TOP,
    DEEP_WATER_BOTTOM,
    SHALLOW_TOP,
    SHALLOW_BOTTOM,
    BEACH_TOP,
    BEACH_BOTTOM,
    STARTER_SLIMES,
    SLIME_BOSS_POS,
    SLIME_RUIN_RECT,
    WILDERNESS_NINJAS,
    RING_NINJAS,
    BOSS_POS,
    NINJA_HIDEOUT_RECT,
    NINJA_HIDEOUT_CENTER,
    VEGETATION_DEAD_START,
    VEGETATION,
    INTERACT_RANGE,
    NINJA_DEATH_PALETTE,
    SLIME_DEATH_PALETTE,
    DEEP_WATER_RECTS,
    TREE_RECTS,
    _gen_vegetation,
    _wrap_text,
)
from game_pkg.game import Game


__all__ = [
    "STARTER_WEAPON",
    "STARTER_ABILITY",
    "DEEP_WATER_TOP",
    "DEEP_WATER_BOTTOM",
    "SHALLOW_TOP",
    "SHALLOW_BOTTOM",
    "BEACH_TOP",
    "BEACH_BOTTOM",
    "STARTER_SLIMES",
    "SLIME_BOSS_POS",
    "SLIME_RUIN_RECT",
    "WILDERNESS_NINJAS",
    "RING_NINJAS",
    "BOSS_POS",
    "NINJA_HIDEOUT_RECT",
    "NINJA_HIDEOUT_CENTER",
    "VEGETATION_DEAD_START",
    "VEGETATION",
    "INTERACT_RANGE",
    "NINJA_DEATH_PALETTE",
    "SLIME_DEATH_PALETTE",
    "DEEP_WATER_RECTS",
    "TREE_RECTS",
    "_gen_vegetation",
    "_wrap_text",
    "Game",
]
